# Generated by Django 4.0b1 on 2021-11-21 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('celular', models.CharField(max_length=200)),
                ('creci', models.CharField(max_length=200)),
                ('dtanasc', models.DateField(blank=True, null=True)),
                ('cidade', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Estadoconser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nomecondominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('endereco', models.CharField(blank=True, max_length=300, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, db_column='UF', max_length=2, null=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Padrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tabelarossheideck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade_em_vida', models.IntegerField(blank=True, db_column='idade_em_vida', null=True)),
                ('a', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('b', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('c', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('d', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('e', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('f', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('h', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Vidautil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('idadevidautil', models.IntegerField(blank=True, db_column='idadeVidaUtil', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valordevenda', models.DecimalField(db_column='valorDeVenda', decimal_places=2, default=0, max_digits=10, verbose_name='Valor de venda')),
                ('idade', models.IntegerField(blank=True)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=200)),
                ('aconstruida', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Área Construída/Útil')),
                ('atotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Área Total')),
                ('dtacadastro', models.DateField(blank=True, db_column='dtaCadastro', null=True, verbose_name='Data de cadastro')),
                ('status', models.CharField(choices=[('1', 'Oferta'), ('2', 'Vendido')], max_length=1)),
                ('corretor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portal.corretor')),
                ('estadoconser', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portal.estadoconser', verbose_name='Estado de Conservação')),
                ('nomecondominio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.nomecondominio', verbose_name='Condominio')),
                ('padrao', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portal.padrao')),
                ('tipo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portal.tipo')),
                ('vidautil', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portal.vidautil', verbose_name='Vida Útil')),
            ],
            options={
                'unique_together': {('padrao', 'tipo', 'nomecondominio', 'estadoconser', 'corretor', 'vidautil')},
            },
        ),
    ]
