# Generated by Django 4.0b1 on 2021-11-22 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='imovel',
            unique_together=set(),
        ),
    ]
